CREATE OR REPLACE TABLE tblBCTC AS
WITH ab AS (
    SELECT
        COALESCE(a."index", b."index") AS "index",
        COALESCE(a."Ticker", b."Ticker") AS "Ticker",
        -- Table A
        TRY(last_day(make_date(
            CAST(split_part(a."index", '/', 2) AS INTEGER),
            CAST(split_part(split_part(a."index", 'Q', 2), '/', 1) AS INTEGER) * 3,
            1))) AS DT,
        a."index",
        a."Ticker",
        a."Chi phí bán hàng", 
        a."Chi phí quản lý doanh nghiệp", 
        a."Chi phí tài chính", 
        a."Công ty kiểm toán", 
        a."Doanh thu hoạt động tài chính", 
        a."Doanh thu thuần về bán hàng và cung cấp dịch vụ", 
        a."Giai đoạn", 
        a."Giá vốn hàng bán", 
        a."Hợp nhất", 
        a."Kiểm toán", 
        a."Lãi cơ bản trên cổ phiếu (VNÐ)", 
        a."Lợi nhuận gộp về bán hàng và cung cấp dịch vụ", 
        a."Lợi nhuận khác", 
        a."Lợi nhuận sau thuế của cổ đông Công ty mẹ", 
        a."Lợi nhuận sau thuế thu nhập doanh nghiệp", 
        a."Lợi nhuận thuần từ hoạt động kinh doanh", 
        a."Phần lợi nhuận/lỗ từ công ty liên kết liên doanh", 
        a."Tổng lợi nhuận kế toán trước thuế", 
        a."Ý kiến kiểm toán",
        -- Table B
        b."Bất động sản đầu tư", 
        b."Các khoản phải thu ngắn hạn", 
        b."Các khoản đầu tư tài chính dài hạn", 
        b."Các khoản đầu tư tài chính ngắn hạn", 
        b."Công ty kiểm toán", 
        b."Giai đoạn", 
        b."Hàng tồn kho", 
        b."Hợp nhất", 
        b."Kiểm toán", 
        b."Lợi nhuận sau thuế chưa phân phối", 
        b."Lợi ích của cổ đông thiểu số", 
        b."Nợ dài hạn", 
        b."Nợ ngắn hạn", 
        b."Nợ phải trả", 
        b."Thặng dư vốn cổ phần", 
        b."Tiền và các khoản tương đương tiền", 
        b."Tài sản cố định", 
        b."Tài sản dài hạn", 
        b."Tài sản ngắn hạn", 
        b."Tài sản ngắn hạn khác", 
        b."Tổng cộng nguồn vốn", 
        b."Tổng cộng tài sản", 
        b."Vốn chủ sở hữu", 
        b."Vốn đầu tư của chủ sở hữu", 
        b."Ý kiến kiểm toán"
    FROM "CherryMon"."main"."bctc_kqkd" a
    FULL OUTER JOIN "CherryMon"."main"."bctc_cdkt" b
        ON a."Ticker" = b."Ticker"
        AND a."index" = b."index"
    WHERE a."Giai đoạn" is not null and b."Giai đoạn" is not null and a."Chi phí bán hàng" is not null
)
SELECT
    COALESCE(ab."index", c."index") AS "Quarter",
    COALESCE(ab."Ticker", c."Ticker") AS "Ticker",
    -- Table A fields
    ab."Chi phí bán hàng", 
    ab."Chi phí quản lý doanh nghiệp", 
    ab."Chi phí tài chính", 
    ab."Công ty kiểm toán" as "Công ty kiểm toán", 
    ab."Doanh thu hoạt động tài chính", 
    ab."Doanh thu thuần về bán hàng và cung cấp dịch vụ", 
    ab."Giai đoạn" as "Giai đoạn (kqkd)", 
    ab."Giá vốn hàng bán", 
    ab."Hợp nhất" as "Hợp nhất (kqkd)", 
    ab."Kiểm toán" as "Kiểm toán (kqkd)", 
    ab."Lãi cơ bản trên cổ phiếu (VNÐ)", 
    ab."Lợi nhuận gộp về bán hàng và cung cấp dịch vụ", 
    ab."Lợi nhuận khác", 
    ab."Lợi nhuận sau thuế của cổ đông Công ty mẹ", 
    ab."Lợi nhuận sau thuế thu nhập doanh nghiệp", 
    ab."Lợi nhuận thuần từ hoạt động kinh doanh", 
    ab."Phần lợi nhuận/lỗ từ công ty liên kết liên doanh", 
    ab."Tổng lợi nhuận kế toán trước thuế", 
    ab."Ý kiến kiểm toán" as "Ý kiến kiểm toán (kqkd)",
    -- Table B fields
    ab."Bất động sản đầu tư", 
    ab."Các khoản phải thu ngắn hạn", 
    ab."Các khoản đầu tư tài chính dài hạn", 
    ab."Các khoản đầu tư tài chính ngắn hạn", 
    ab."Công ty kiểm toán" as "Công ty kiểm toán (cdkt)", 
    ab."Giai đoạn" as "Giai đoạn (cdkt)", 
    ab."Hàng tồn kho", 
    ab."Hợp nhất" as "Hợp nhất (cdkt)", 
    ab."Kiểm toán" as "Kiểm toán (cdkt)", 
    ab."Lợi nhuận sau thuế chưa phân phối", 
    ab."Lợi ích của cổ đông thiểu số", 
    ab."Nợ dài hạn", 
    ab."Nợ ngắn hạn", 
    ab."Nợ phải trả", 
    ab."Thặng dư vốn cổ phần", 
    ab."Tiền và các khoản tương đương tiền", 
    ab."Tài sản cố định", 
    ab."Tài sản dài hạn", 
    ab."Tài sản ngắn hạn", 
    ab."Tài sản ngắn hạn khác", 
    ab."Tổng cộng nguồn vốn", 
    ab."Tổng cộng tài sản", 
    ab."Vốn chủ sở hữu", 
    ab."Vốn đầu tư của chủ sở hữu", 
    ab."Ý kiến kiểm toán" as "Ý kiến kiểm toán (cdkt)",
    -- Table C fields
    c."Chỉ số giá thị trường trên giá trị sổ sách (P/B)", 
    c."Chỉ số giá thị trường trên thu nhập (P/E)", 
    c."Công ty kiểm toán" as "Công ty kiểm toán (cstc)", 
    c."Giai đoạn" as "Giai đoạn (cstc)", 
    c."Giá trị sổ sách của cổ phiếu (BVPS)", 
    c."Hợp nhất" as "Hợp nhất (cstc)", 
    c."Khả năng thanh toán lãi vay" as "Khả năng thanh toán lãi vay (TIE)", 
    c."Kiểm toán" as "Kiểm toán (cstc)", 
    c."Thu nhập trên mỗi cổ phần của 4 quý gần nhất (EPS)", 
    c."Tỷ suất lợi nhuận gộp biên" as "Tỷ suất lợi nhuận gộp biên (GPM)", 
    c."Tỷ suất lợi nhuận trên vốn chủ sở hữu bình quân (ROEA)", 
    c."Tỷ suất sinh lợi trên doanh thu thuần" as "Tỷ suất sinh lợi trên doanh thu thuần (ROS)", 
    c."Tỷ suất sinh lợi trên tổng tài sản bình quân (ROAA)", 
    c."Tỷ số Nợ trên Tổng tài sản" as "Tỷ số Nợ trên Tổng tài sản (DAR)", 
    c."Tỷ số Nợ vay trên Vốn chủ sở hữu" as "Tỷ số Nợ vay trên Vốn chủ sở hữu (D/E)", 
    c."Tỷ số thanh toán hiện hành (ngắn hạn)" as "Tỷ số thanh toán hiện hành (Current Ratio)", 
    c."Ý kiến kiểm toán" as "Ý kiến kiểm toán (cstc)"
FROM ab
FULL OUTER JOIN "CherryMon"."main"."bctc_cstc" c
    ON ab."Ticker" = c."Ticker"
    AND ab."index" = c."index"
WHERE c."Giai đoạn" is not null;
