"""
facebook_community_playwright.py
--------------------------------
Experimental Facebook community collector using Playwright persistent profile.

Goal
----
For a target Facebook profile/page (default: Barchart), this script:
1. Opens a dedicated persistent Chrome profile.
2. Reuses the Facebook login session between runs.
3. Navigates to the target page.
4. Intercepts timeline GraphQL traffic generated by Facebook itself.
5. Collects up to N recent post-like records from GraphQL responses.
6. Saves raw GraphQL responses + normalized JSON/CSV.

Why this design
---------------
This avoids manually copying:
    FB_COOKIE
    FB_DTSG
    FB_LSD

The browser handles its own cookies/session/CSRF values.

IMPORTANT
---------
- This uses Facebook's INTERNAL web GraphQL traffic, not the official Graph API.
- Response shape and internal query names can change at any time.
- Use only your own authorized Facebook session and comply with Meta/Facebook terms.
- Do NOT use your normal Chrome user-data directory while Chrome is already open.
  Use a dedicated Playwright profile directory.

Install
-------
    pip install playwright pandas
    playwright install chromium

Run (first time, interactive login)
-----------------------------------
    python facebook_community_playwright.py --limit 5

The first run opens Chrome. Log in to Facebook manually if needed.
The dedicated profile is saved by default under:
    ./Build/browser_profiles/facebook

Later runs reuse the same login session.

Examples
--------
    python facebook_community_playwright.py --limit 5

    python facebook_community_playwright.py \
        --url https://www.facebook.com/Barchart \
        --page-name Barchart \
        --limit 5

    python facebook_community_playwright.py \
        --profile-dir C:\\Github\\CherryStock\\Build\\browser_profiles\\facebook \
        --limit 5

Outputs
-------
    Barchart_facebook_posts.json
    Barchart_facebook_posts.csv
    Barchart_facebook_graphql_raw.json
"""

from __future__ import annotations

import argparse
import html
import json
import re
import time
from pathlib import Path
from typing import Any

try:
    import pandas as pd
except ImportError:
    pd = None

from playwright.sync_api import (
    BrowserContext,
    Page,
    Request,
    Response,
    sync_playwright,
)


DEFAULT_URL = "https://www.facebook.com/Barchart"
DEFAULT_PAGE_NAME = "Barchart"
DEFAULT_PROFILE_DIR = str(
    Path("Build") / "browser_profiles" / "facebook"
)

TIMELINE_FRIENDLY_NAMES = {
    "ProfileCometTimelineFeedRefetchQuery",
}

GRAPHQL_PATH = "/api/graphql/"


class FacebookCollectorError(RuntimeError):
    pass


def walk_json(value: Any):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from walk_json(child)
    elif isinstance(value, list):
        for child in value:
            yield from walk_json(child)


def normalize_text(text: str) -> str:
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def extract_best_text(obj: Any) -> str | None:
    """
    Facebook internal GraphQL schemas vary frequently.
    Search recursively for plausible post text and pick the longest candidate.
    """
    candidates: list[str] = []

    for node in walk_json(obj):
        if not isinstance(node, dict):
            continue

        for key in ("message", "text", "body", "title"):
            value = node.get(key)

            if isinstance(value, str):
                s = normalize_text(value)
                if len(s) >= 10:
                    candidates.append(s)

            elif isinstance(value, dict):
                nested = value.get("text")
                if isinstance(nested, str):
                    s = normalize_text(nested)
                    if len(s) >= 10:
                        candidates.append(s)

    if not candidates:
        return None

    # Prefer substantive long text over UI labels.
    return max(candidates, key=len)


def find_facebook_permalink(obj: Any) -> str | None:
    for node in walk_json(obj):
        if not isinstance(node, dict):
            continue

        for key in (
            "url",
            "permalink_url",
            "story_url",
            "wwwURL",
            "www_url",
        ):
            value = node.get(key)

            if not isinstance(value, str):
                continue

            if "facebook.com" not in value:
                continue

            if (
                "/posts/" in value
                or "/permalink/" in value
                or "story_fbid=" in value
                or "/photo/" in value
                or "/videos/" in value
            ):
                return value

    return None


def find_author(obj: Any) -> tuple[str | None, str | None]:
    """
    Heuristic author extraction.
    """
    for node in walk_json(obj):
        if not isinstance(node, dict):
            continue

        name = node.get("name")
        node_id = node.get("id")

        typename = str(node.get("__typename") or "")

        if (
            isinstance(name, str)
            and name.strip()
            and (
                "Actor" in typename
                or "User" in typename
                or "Page" in typename
                or "Profile" in typename
            )
        ):
            return str(node_id) if node_id is not None else None, name.strip()

    return None, None


def find_creation_time(obj: Any) -> Any:
    for node in walk_json(obj):
        if not isinstance(node, dict):
            continue

        for key in (
            "creation_time",
            "created_time",
            "publish_time",
            "creation_timestamp",
        ):
            if node.get(key) is not None:
                return node.get(key)

    return None


def find_feedback_counts(obj: Any) -> dict[str, Any]:
    """
    Best-effort reaction/comment/share count extraction.
    """
    result = {
        "reaction_count": None,
        "comment_count": None,
        "share_count": None,
    }

    for node in walk_json(obj):
        if not isinstance(node, dict):
            continue

        # Direct count-ish fields
        for key, target in (
            ("reaction_count", "reaction_count"),
            ("comment_count", "comment_count"),
            ("share_count", "share_count"),
            ("total_count", None),
        ):
            if target and result[target] is None:
                value = node.get(key)
                if isinstance(value, (int, float)):
                    result[target] = value

        # Common nested shapes such as comments.total_count
        for nested_key, target in (
            ("comments", "comment_count"),
            ("reactors", "reaction_count"),
            ("reactions", "reaction_count"),
            ("shares", "share_count"),
        ):
            nested = node.get(nested_key)
            if (
                result[target] is None
                and isinstance(nested, dict)
                and isinstance(nested.get("total_count"), (int, float))
            ):
                result[target] = nested["total_count"]

    return result


def story_identity(obj: dict[str, Any]) -> str | None:
    for key in (
        "post_id",
        "story_id",
        "legacy_fbid",
        "id",
    ):
        value = obj.get(key)
        if isinstance(value, (str, int)) and str(value):
            return str(value)

    permalink = find_facebook_permalink(obj)
    if permalink:
        return permalink

    text = extract_best_text(obj)
    if text:
        return text[:200]

    return None


def looks_like_story(obj: dict[str, Any]) -> bool:
    keys = set(obj.keys())

    if keys & {
        "post_id",
        "story_id",
        "legacy_fbid",
        "comet_sections",
        "feedback",
        "creation_time",
    }:
        return True

    typename = str(obj.get("__typename") or "")
    if "Story" in typename or "FeedUnit" in typename:
        return True

    permalink = find_facebook_permalink(obj)
    if permalink:
        return True

    return False


def extract_posts_from_document(
    document: dict[str, Any],
    *,
    page_name: str,
) -> list[dict[str, Any]]:
    posts: list[dict[str, Any]] = []
    seen: set[str] = set()

    for obj in walk_json(document):
        if not isinstance(obj, dict):
            continue

        if not looks_like_story(obj):
            continue

        identity = story_identity(obj)
        if not identity or identity in seen:
            continue

        text = extract_best_text(obj)
        permalink = find_facebook_permalink(obj)

        # Filter out weak GraphQL/UI candidates.
        if not text and not permalink:
            continue

        seen.add(identity)

        author_id, author_name = find_author(obj)
        counts = find_feedback_counts(obj)

        post_id = (
            obj.get("post_id")
            or obj.get("story_id")
            or obj.get("legacy_fbid")
            or obj.get("id")
        )

        posts.append(
            {
                "source": "Facebook",
                "page_name": page_name,
                "post_id": post_id,
                "author_id": author_id,
                "author_name": author_name,
                "creation_time": find_creation_time(obj),
                "content": text,
                "permalink": permalink,
                **counts,
            }
        )

    return posts


class FacebookPlaywrightCollector:
    def __init__(
        self,
        *,
        profile_dir: str,
        target_url: str,
        page_name: str,
        headless: bool = False,
    ) -> None:
        self.profile_dir = str(Path(profile_dir).resolve())
        self.target_url = target_url
        self.page_name = page_name
        self.headless = headless

        self.raw_graphql: list[dict[str, Any]] = []
        self.posts: list[dict[str, Any]] = []
        self.seen_post_keys: set[str] = set()

    def _post_key(self, post: dict[str, Any]) -> str:
        return str(
            post.get("post_id")
            or post.get("permalink")
            or post.get("content")
            or ""
        )

    def _merge_posts(self, items: list[dict[str, Any]]) -> None:
        for item in items:
            key = self._post_key(item)
            if not key or key in self.seen_post_keys:
                continue

            self.seen_post_keys.add(key)
            self.posts.append(item)

    def _handle_response(self, response: Response) -> None:
        if GRAPHQL_PATH not in response.url:
            return

        request = response.request
        post_data = request.post_data or ""

        # Prioritize timeline requests but keep other GraphQL responses too,
        # because Facebook sometimes moves story data across queries.
        friendly_name = request.headers.get("x-fb-friendly-name")

        relevant = (
            friendly_name in TIMELINE_FRIENDLY_NAMES
            or "ProfileCometTimelineFeedRefetchQuery" in post_data
        )

        try:
            text = response.text()
        except Exception:
            return

        docs = parse_facebook_graphql_text(text)
        if not docs:
            return

        raw_entry = {
            "url": response.url,
            "friendly_name": friendly_name,
            "relevant_timeline_request": relevant,
            "documents": docs,
        }
        self.raw_graphql.append(raw_entry)

        for doc in docs:
            extracted = extract_posts_from_document(
                doc,
                page_name=self.page_name,
            )
            self._merge_posts(extracted)

    def collect(
        self,
        *,
        limit: int = 5,
        max_scrolls: int = 12,
        scroll_wait_ms: int = 1800,
        login_wait_seconds: int = 180,
    ) -> list[dict[str, Any]]:
        Path(self.profile_dir).mkdir(parents=True, exist_ok=True)

        with sync_playwright() as p:
            context = p.chromium.launch_persistent_context(
                self.profile_dir,
                channel="chrome",
                headless=self.headless,
                viewport={"width": 1500, "height": 1000},
            )

            page = (
                context.pages[0]
                if context.pages
                else context.new_page()
            )

            page.on("response", self._handle_response)

            page.goto(
                self.target_url,
                wait_until="domcontentloaded",
                timeout=120_000,
            )

            if self._looks_logged_out(page):
                if self.headless:
                    context.close()
                    raise FacebookCollectorError(
                        "Facebook profile is not logged in. "
                        "Run once without --headless and log in manually."
                    )

                print("\nFacebook login is required.")
                print(
                    "Log in manually in the opened Chrome window. "
                    "This dedicated profile will preserve the session."
                )
                print(
                    f"Waiting up to {login_wait_seconds} seconds..."
                )

                deadline = time.time() + login_wait_seconds

                while time.time() < deadline:
                    page.wait_for_timeout(2000)

                    if not self._looks_logged_out(page):
                        print("Login detected.")
                        page.goto(
                            self.target_url,
                            wait_until="domcontentloaded",
                            timeout=120_000,
                        )
                        break
                else:
                    context.close()
                    raise FacebookCollectorError(
                        "Login was not detected before timeout."
                    )

            # Allow initial feed requests to finish.
            page.wait_for_timeout(4000)

            for scroll_no in range(max_scrolls + 1):
                if len(self.posts) >= limit:
                    break

                if scroll_no >= max_scrolls:
                    break

                print(
                    f"[Facebook] scroll={scroll_no + 1}/{max_scrolls} "
                    f"candidate_posts={len(self.posts)}"
                )

                page.evaluate(
                    "window.scrollBy(0, Math.max(window.innerHeight * 2.5, 1800))"
                )

                page.wait_for_timeout(scroll_wait_ms)

            context.close()

        return self.posts[:limit]

    @staticmethod
    def _looks_logged_out(page: Page) -> bool:
        url = page.url.lower()

        if "/login" in url:
            return True

        # Simple browser-level checks; avoid relying on language-specific UI.
        cookies = page.context.cookies("https://www.facebook.com")
        cookie_names = {c["name"] for c in cookies}

        return "c_user" not in cookie_names


def parse_facebook_graphql_text(
    text: str,
) -> list[dict[str, Any]]:
    text = text.strip()

    if text.startswith("for (;;);"):
        text = text[len("for (;;);"):].lstrip()

    docs: list[dict[str, Any]] = []

    try:
        obj = json.loads(text)

        if isinstance(obj, dict):
            return [obj]

        if isinstance(obj, list):
            return [
                item
                for item in obj
                if isinstance(item, dict)
            ]
    except json.JSONDecodeError:
        pass

    # Facebook frequently returns newline-separated GraphQL payloads.
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue

        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue

        if isinstance(obj, dict):
            docs.append(obj)

    return docs


def save_outputs(
    *,
    page_name: str,
    posts: list[dict[str, Any]],
    raw_graphql: list[dict[str, Any]],
    output_dir: str,
) -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    prefix = re.sub(
        r"[^A-Za-z0-9_.-]+",
        "_",
        page_name,
    )

    raw_path = out / f"{prefix}_facebook_graphql_raw.json"
    raw_path.write_text(
        json.dumps(
            raw_graphql,
            indent=2,
            ensure_ascii=False,
            default=str,
        ),
        encoding="utf-8",
    )

    json_path = out / f"{prefix}_facebook_posts.json"
    json_path.write_text(
        json.dumps(
            posts,
            indent=2,
            ensure_ascii=False,
            default=str,
        ),
        encoding="utf-8",
    )

    print("\nSaved:")
    print(" ", raw_path)
    print(" ", json_path)

    if pd is not None:
        csv_path = out / f"{prefix}_facebook_posts.csv"

        pd.DataFrame(posts).to_csv(
            csv_path,
            index=False,
            encoding="utf-8-sig",
        )

        print(" ", csv_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Experimental Facebook page/profile collector using "
            "Playwright persistent Chrome profile."
        )
    )

    parser.add_argument(
        "--url",
        default=DEFAULT_URL,
        help=f"Target Facebook URL. Default: {DEFAULT_URL}",
    )

    parser.add_argument(
        "--page-name",
        default=DEFAULT_PAGE_NAME,
        help=f"Output/page label. Default: {DEFAULT_PAGE_NAME}",
    )

    parser.add_argument(
        "--profile-dir",
        default=DEFAULT_PROFILE_DIR,
        help=(
            "Dedicated persistent Chrome profile directory. "
            f"Default: {DEFAULT_PROFILE_DIR}"
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=5,
        help="Number of posts to collect. Default: 5",
    )

    parser.add_argument(
        "--max-scrolls",
        type=int,
        default=12,
        help="Maximum timeline scrolls. Default: 12",
    )

    parser.add_argument(
        "--scroll-wait-ms",
        type=int,
        default=1800,
        help="Wait between scrolls in milliseconds. Default: 1800",
    )

    parser.add_argument(
        "--login-wait-seconds",
        type=int,
        default=180,
        help="First-run manual login timeout. Default: 180",
    )

    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run without visible browser. Requires an already logged-in profile.",
    )

    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory. Default: current directory",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    print("=" * 80)
    print("Facebook Playwright collector")
    print("Target URL :", args.url)
    print("Page name  :", args.page_name)
    print("Profile    :", Path(args.profile_dir).resolve())
    print("Limit      :", args.limit)
    print("Headless   :", args.headless)
    print("=" * 80)

    collector = FacebookPlaywrightCollector(
        profile_dir=args.profile_dir,
        target_url=args.url,
        page_name=args.page_name,
        headless=args.headless,
    )

    posts = collector.collect(
        limit=args.limit,
        max_scrolls=args.max_scrolls,
        scroll_wait_ms=args.scroll_wait_ms,
        login_wait_seconds=args.login_wait_seconds,
    )

    print(f"\nCollected {len(posts)} candidate post(s).")

    for i, post in enumerate(posts, start=1):
        print("\n" + "=" * 80)
        print(f"POST {i}")
        print("post_id       :", post.get("post_id"))
        print("author        :", post.get("author_name"))
        print("creation_time :", post.get("creation_time"))
        print("permalink     :", post.get("permalink"))
        print("reactions     :", post.get("reaction_count"))
        print("comments      :", post.get("comment_count"))
        print("shares        :", post.get("share_count"))
        print(
            "content       :",
            (post.get("content") or "")[:1200],
        )

    save_outputs(
        page_name=args.page_name,
        posts=posts,
        raw_graphql=collector.raw_graphql,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()